project: 
  type: website
  output-dir: docs

website:
  title: "Yang Zeng's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "Complex Data Type Analysis"
            file: complex_data_type_analysis/complext_data_type_analysis.qmd
    right:
      - icon: github 
        href: https://github.com/yangyin-zeng/YangZeng-portfolio.git      
format:
  html:
    theme: journal
    highlight: zenburn
    css: styles.css
    toc: FALSE
